![logo.png]()


<div align="center">
  <font color="blue"><h1>Lists in Python</h1></font>
</div>

### ========================================================================================

1. **What are lists in Python?**

  Lists in Python are ordered collections of items, where each item can be of any data type. They are one of the most versatile and commonly used data structures in Python. Lists are defined using square brackets [], and their elements are separated by commas.

2. Explain the working of lists:

  Lists in Python maintain the order of elements, meaning the position of an element in the list is preserved. Elements in a list can be accessed using indexing, and you can perform various operations on lists such as appending, inserting, updating, and deleting elements.

3. **What are List Containers?**

  List containers refer to data structures that hold a collection of items in an ordered sequence. Lists in Python are one of the primary examples of list containers. They provide methods and functionality to manipulate the stored items easily.

4. **What is dynamic insertion in the context of lists?**

  Dynamic insertion in the context of lists refers to the ability to add or insert items into a list without requiring predefined memory allocation. In Python, lists are dynamic in nature, which means you can add elements at any position without worrying about memory management.

5. **What are the advantages and disadvantages of lists?**

  ***Advantages of lists:***

  Dynamic size: Lists can grow or shrink as needed.
  Versatile: Lists can store heterogeneous data types.
  Order preservation: Elements are stored in the order they are added.
  Built-in methods: Lists come with various built-in methods for manipulation.

  **Disadvantages of lists:**

    Slower than arrays: Access and manipulation can be slower compared to arrays.
    Higher memory usage: Lists consume more memory due to additional metadata.
    Limited performance for large datasets: Lists may not be the most efficient for very large datasets.
  
5. **How is storage space allocated to lists? How dynamic size works?**

  Lists in Python are implemented as dynamic arrays. Initially, a small amount of memory is allocated to hold elements. As you append more items, if the list grows beyond its current allocated size, a new larger memory block is allocated, and elements are copied to the new block. This process allows lists to dynamically resize and accommodate more elements as needed. The growth factor for dynamic resizing can vary based on Python's implementation details.

## Ways to Create a List

In [1]:
# Method 1: Using square brackets []
empty_list = []  # Creating an empty list
print("Empty list:", empty_list)

Empty list: []

In [2]:
# Method 2: Initializing with values
numbers = [1, 2, 3, 4, 5]  # Creating a list of numbers
print("List of numbers:", numbers)

List of numbers: [1, 2, 3, 4, 5]

In [3]:
# Method 3: Using list() constructor
fruits = list(["apple", "banana", "orange"])  # Creating a list of fruits
print("List of fruits:", fruits)

List of fruits: ['apple', 'banana', 'orange']

In [4]:
# Method 4: Using list comprehension
squares = [x ** 2 for x in range(1, 6)]  # Creating a list of squares
print("List of squares:", squares)

List of squares: [1, 4, 9, 16, 25]

In [5]:
# Method 5: Using multiplication (*)
repeated_list = ["hello"] * 3  # Creating a list with repeated elements
print("Repeated list:", repeated_list)

Repeated list: ['hello', 'hello', 'hello']

In [6]:
# Method 6: Creating a list of characters from a string
word = "Python"
characters = list(word)  # Creating a list of characters
print("List of characters:", characters)

List of characters: ['P', 'y', 't', 'h', 'o', 'n']

In [7]:
# Method 7: Nested lists
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # Creating a nested list
print("Nested list (matrix):", matrix)

Nested list (matrix): [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# Method 8: Using the range() function
range_list = list(range(1, 6))  # Creating a list using range
print("Range list:", range_list)

Range list: [1, 2, 3, 4, 5]

In [9]:
# Method 9: Using split() to create a list from a string
sentence = "This is a sentence"
words = sentence.split()  # Creating a list of words
print("List of words:", words)

List of words: ['This', 'is', 'a', 'sentence']

In [10]:
# Method 10: Using append() to add elements
my_list = []  # Creating an empty list
my_list.append(10)  # Adding an element using append
print("List after appending:", my_list)

List after appending: [10]

In [11]:
# Method 11: Using extend() to add multiple elements
initial_list = [1, 2, 3]
additional_elements = [4, 5, 6]
initial_list.extend(additional_elements)  # Extending the list
print("List after extending:", initial_list)

List after extending: [1, 2, 3, 4, 5, 6]

In [12]:
# Method 12: Using list comprehension with conditions
even_numbers = [x for x in range(1, 11) if x % 2 == 0]  # Creating a list of even numbers
print("List of even numbers:", even_numbers)

List of even numbers: [2, 4, 6, 8, 10]

In [13]:
# Method 13: Using list() with map()
numbers_str = ["1", "2", "3", "4", "5"]
numbers_int = list(map(int, numbers_str))  # Converting strings to integers
print("List of integers from strings:", numbers_int)

List of integers from strings: [1, 2, 3, 4, 5]

In [14]:
# Method 14: Creating a list with different data types
mixed_list = [1, "hello", 3.14, True, [1, 2, 3]]  # Creating a mixed data type list
print("Mixed data type list:", mixed_list)

Mixed data type list: [1, 'hello', 3.14, True, [1, 2, 3]]

In [15]:
# Method 15: Using a constructor to create an empty list
empty_list = list()  # Creating an empty list using the constructor
print("Empty list using constructor:", empty_list)

Empty list using constructor: []

In [16]:
# Method 16: Using list comprehension with conditional expression
squared_even = [x ** 2 if x % 2 == 0 else x for x in range(1, 6)]  # Creating a list with condition
print("List with squared even numbers:", squared_even)

List with squared even numbers: [1, 4, 3, 16, 5]

In [17]:
# Method 17: Using zip() to create a list of tuples
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 22]
name_age_tuples = list(zip(names, ages))  # Creating a list of tuples
print("List of name-age tuples:", name_age_tuples)

List of name-age tuples: [('Alice', 25), ('Bob', 30), ('Charlie', 22)]

In [18]:
# Method 18: Using list() with set or tuple
unique_elements = list(set([1, 2, 2, 3, 3, 4]))  # Creating a list from a set
print("List from a set:", unique_elements)

List from a set: [1, 2, 3, 4]

In [19]:
# Method 19: Using comprehension with nested loops
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_matrix = [num for row in matrix for num in row]  # Flattening a nested list
print("Flattened matrix:", flattened_matrix)

Flattened matrix: [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
# Method 20: Creating a list using input from the user
num_elements = int(input("Enter the number of elements: "))
user_list = [int(input("Enter element {}: ".format(i+1))) for i in range(num_elements)]
print("User-created list:", user_list)

Enter the number of elements: 3
Enter element 1: 12
Enter element 2: 35
Enter element 3: 5
User-created list: [12, 35, 5]

### ========================================================================================

## Inserting Elements to Lists

In [21]:
# Method 1: Using append() to add elements
my_list = []  # Creating an empty list
my_list.append(10)  # Adding an element using append
print("List after appending:", my_list)

List after appending: [10]

In [22]:
# Method 2: Using extend() to add multiple elements
initial_list = [1, 2, 3]
additional_elements = [4, 5, 6]
initial_list.extend(additional_elements)  # Extending the list
print("List after extending:", initial_list)

List after extending: [1, 2, 3, 4, 5, 6]

In [23]:
# Method 3: Using insert() to add elements at a specific position
numbers = [1, 2, 4, 5]
numbers.insert(2, 3)  # Inserting 3 at index 2
print("List after inserting:", numbers)

List after inserting: [1, 2, 3, 4, 5]

In [24]:
# Method 4: Using += operator to extend a list
my_list = [1, 2, 3]
my_list += [4, 5]  # Extending the list using +=
print("List after extending with +=:", my_list)

List after extending with +=: [1, 2, 3, 4, 5]

### ========================================================================================

## Ways to remove elements from Lists

In [25]:
# Method 1: Using del statement to remove elements by index
numbers = [1, 2, 3, 4, 5]
del numbers[2]  # Removing element at index 2
print("List after removing element:", numbers)

List after removing element: [1, 2, 4, 5]

In [26]:
# Method 2: Using remove() to remove elements by value
fruits = ["apple", "banana", "orange"]
fruits.remove("banana")  # Removing "banana" from the list
print("List after removing element:", fruits)

List after removing element: ['apple', 'orange']

In [27]:
# Method 3: Using pop() to remove elements by index and return the value
colors = ["red", "green", "blue"]
removed_color = colors.pop(1)  # Removing element at index 1 ("green")
print("Removed color:", removed_color)
print("List after pop:", colors)

Removed color: green
List after pop: ['red', 'blue']

In [28]:
# Method 4: Using pop() without an index to remove the last element
letters = ["a", "b", "c"]
removed_letter = letters.pop()  # Removing the last element ("c")
print("Removed letter:", removed_letter)
print("List after pop:", letters)

Removed letter: c
List after pop: ['a', 'b']

In [29]:
# Method 5: Using clear() to remove all elements and make the list empty
animals = ["dog", "cat", "elephant"]
animals.clear()  # Removing all elements
print("List after clearing:", animals)

List after clearing: []

In [30]:
# Method 6: Using list comprehension to remove elements with a condition
grades = [85, 90, 75, 95, 60]
passing_grades = [x for x in grades if x >= 70]  # Removing grades below 70
print("List of passing grades:", passing_grades)

List of passing grades: [85, 90, 75, 95]

In [31]:
# Method 7: Using filter() and lambda to remove elements
numbers = [1, 2, 3, 4, 5]
filtered_numbers = list(filter(lambda x: x != 2, numbers))  # Removing 2
print("List after filtering:", filtered_numbers)

List after filtering: [1, 3, 4, 5]

In [32]:
# Method 8: Using slicing to remove a range of elements
colors = ["red", "green", "blue", "yellow", "orange"]
colors[1:4] = []  # Removing elements from index 1 to 3
print("List after slicing:", colors)

List after slicing: ['red', 'orange']

### ========================================================================================

### List Methods & Built-in Functions

| Method / Function  | Description                                                 |
|--------------------|-------------------------------------------------------------|
| append()           | Adds an element to the end of the list                     |
| extend()           | Adds elements from another list to the end                 |
| insert()           | Inserts an element at a specified index in the list        |
| remove()           | Removes the first occurrence of a specified element        |
| pop()              | Removes and returns an element from a specified index      |
| index()            | Returns the index of the first occurrence of an element    |
| count()            | Returns the number of times an element appears             |
| sort()             | Sorts the list in ascending order (in place)               |
| reverse()          | Reverses the order of elements in the list (in place)      |
| clear()            | Removes all elements from the list                         |
| copy()             | Returns a shallow copy of the list                        |
| len()              | Returns the number of elements in the list                 |
| min()              | Returns the smallest element in the list                   |
| max()              | Returns the largest element in the list                    |
| sum()              | Returns the sum of all elements in the list                |
| ord()              | Returns the Unicode code point of the given character      |
| cmp()              | Compares two lists and returns 1 if the first is "greater" |
| all()              | Returns True if all elements are true or if the list is empty |
| any()              | Returns True if any element is true or if the list is empty |
| enumerate()        | Returns an enumerate object of index-value pairs           |
| filter()           | Filters elements based on a function and returns an iterator |
| map()              | Applies a function to items and returns an iterator       |
| zip()              | Combines multiple iterables into tuples at the same index   |

In [33]:
# index() Method
my_list = [1, 2, 3, 2]
index_of_2 = my_list.index(2)
print(index_of_2)

1

In [34]:
# count() Method
my_list = [1, 2, 3, 2]
count_of_2 = my_list.count(2)
print(count_of_2)

2

In [35]:
# sort() Method
my_list = [3, 1, 2]
my_list.sort()
print(my_list)

[1, 2, 3]

In [36]:
# reverse() Method
my_list = [1, 2, 3]
my_list.reverse()
print(my_list)

[3, 2, 1]

In [37]:

# clear() Method
my_list = [1, 2, 3]
my_list.clear()
print(my_list)

[]

In [38]:
# copy() Method
my_list = [1, 2, 3]
new_list = my_list.copy()
print(new_list)

[1, 2, 3]

In [39]:
# len() Function
numbers = [1, 2, 3, 4, 5]
length = len(numbers)
print(length)

5

In [40]:
# min() Function
numbers = [3, 1, 4, 2, 5]
minimum = min(numbers)
print(minimum)

1

In [41]:
# max() Function
numbers = [3, 1, 4, 2, 5]
maximum = max(numbers)
print(maximum)

5

In [42]:
# sum() Function
numbers = [1, 2, 3, 4, 5]
total = sum(numbers)
print(total)

15

In [43]:

# ord() Function
character = 'A'
unicode_code = ord(character)
print(unicode_code)

65

In [44]:
# all() Function
bool_list = [True, True, False]
all_true = all(bool_list)
print(all_true)

False

In [45]:
# any() Function
bool_list = [True, False, False]
any_true = any(bool_list)
print(any_true)

True

In [46]:
# enumerate() Function
letters = ['A', 'B', 'C']
for index, value in enumerate(letters):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: A
Index: 1, Value: B
Index: 2, Value: C

In [47]:
# filter() Function
numbers = [1, 2, 3, 4, 5, 6]
filtered = filter(lambda x: x % 2 == 0, numbers)
filtered_list = list(filtered)
print(filtered_list)

[2, 4, 6]

In [48]:
# map() Function
numbers = [1, 2, 3, 4, 5]
mapped = map(lambda x: x * 2, numbers)
mapped_list = list(mapped)
print(mapped_list)

[2, 4, 6, 8, 10]

In [49]:
# zip() Function
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
zipped = zip(numbers, letters)
zipped_list = list(zipped)
print(zipped_list)

[(1, 'A'), (2, 'B'), (3, 'C')]

In [50]:
#reduce example

In [51]:
from functools import reduce

# Using reduce() to calculate the sum of elements in a list
numbers = [1, 2, 3, 4, 5]
total_sum = reduce(lambda x, y: x + y, numbers)
print(total_sum)

15

### ========================================================================================

## Slicing

Slicing is a technique used to extract a portion of a sequence, such as a list, string, or tuple, by specifying a range of indices. It allows you to create a new sequence containing the selected elements. Slicing is done using square brackets and the colon : operator.

Here are examples of slicing for lists, strings, and tuples:

Slicing for Lists:

In [52]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Extract elements from index 2 (inclusive) to index 5 (exclusive)
sliced_list = my_list[2:5]
print(sliced_list)  # Output: [3, 4, 5]

[3, 4, 5]

Slicing Strings

In [53]:
my_string = "Hello, World!"

# Extract characters from index 7 (inclusive) to index 12 (exclusive)
sliced_string = my_string[7:12]
print(sliced_string)  # Output: "World"

World

Slicing for Tuples:

In [54]:
my_tuple = (10, 20, 30, 40, 50)

# Extract elements from index 1 (inclusive) to index 4 (exclusive)
sliced_tuple = my_tuple[1:4]
print(sliced_tuple)  # Output: (20, 30, 40)

(20, 30, 40)

### ========================================================================================

## Comprehensions

Comprehensions in Python are used to create new sequences, such as lists, dictionaries, and sets, in a concise and expressive way. They provide a more readable and efficient approach to generate sequences compared to using traditional loops and appending or adding elements manually. Comprehensions offer several benefits:

Conciseness: Comprehensions allow you to express complex operations in a single line of code, making your code more compact and easier to understand.

Readability: Comprehensions use a declarative style that closely resembles the mathematical notation for sets and lists. This makes the code more intuitive and readable, especially for simple operations.

Reduced Looping: Comprehensions encapsulate the loop logic within a compact syntax, eliminating the need for separate loop constructs. This leads to cleaner code and reduces the chances of introducing errors in loop iterations.

Performance: Comprehensions are often more efficient than traditional loops because they are implemented internally using optimized mechanisms. This can result in faster execution and better performance for large sequences.

Inline Transformation: Comprehensions allow you to apply transformations or filters to each element of a sequence while generating the new sequence. This makes it easy to perform operations like mapping, filtering, and applying conditions in a single step.

Overall, comprehensions enhance code readability, reduce the lines of code required, and improve the maintainability and efficiency of your programs, making them a preferred choice for creating sequences in Python.

List Comprehension:

In [55]:
# List comprehension to create a list of squares of numbers from 1 to 5
squares = [x**2 for x in range(1, 6)]
print(squares)  # Output: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]

Dictionary Comprehension:

In [56]:
# Dictionary comprehension to create a dictionary of squares for numbers from 1 to 5
squares_dict = {x: x**2 for x in range(1, 6)}
print(squares_dict)  # Output: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

Set Comprehension:

In [57]:
# Set comprehension to create a set of squares for numbers from 1 to 5
squares_set = {x**2 for x in range(1, 6)}
print(squares_set)  # Output: {1, 4, 9, 16, 25}

{1, 4, 9, 16, 25}

Inverting Dictionary:

In [58]:
d1 = {101:'gfg',103:'practice',102:'ide'}
d2 = {v:k for (k,v) in d1.items() }

print(d2)

{'gfg': 101, 'practice': 103, 'ide': 102}

# Problems!

## 1. Seperate Even & Odd

In [59]:
def separate_even_odd(numbers):
    even_numbers = []  # List to store even numbers
    odd_numbers = []   # List to store odd numbers

    # Iterate through each number in the input list
    for num in numbers:
        if num % 2 == 0:  # Check if the number is even
            even_numbers.append(num)  # Add even number to the even_numbers list
        else:
            odd_numbers.append(num)   # Add odd number to the odd_numbers list

    return even_numbers, odd_numbers  # Return the two separate lists

# Example list of numbers
numbers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Separate even and odd numbers using the function
even_numbers, odd_numbers = separate_even_odd(numbers_list)

# Print the separate lists of even and odd numbers
print("Even numbers:", even_numbers)
print("Odd numbers:", odd_numbers)

Even numbers: [2, 4, 6, 8]
Odd numbers: [1, 3, 5, 7, 9]

### ========================================================================================

## 2 . Get Smaller Number

In [60]:
# Function to get a list of numbers smaller than a given value
def get_smaller_numbers(input_list, threshold):
    smaller_numbers = []  # List to store numbers smaller than the threshold

    # Iterate through each element in the input list
    for element in input_list:
        if element < threshold:
            smaller_numbers.append(element)  # Add the element to the list if it's smaller

    return smaller_numbers

# Given list of numbers and a threshold value
number_list = [8, 100, 20, 40, 3, 7]
threshold_value = 10

# Get the list of numbers smaller than the threshold using the function
smaller_numbers_list = get_smaller_numbers(number_list, threshold_value)

# Print the list of smaller numbers
print("Numbers smaller than", threshold_value, ":", smaller_numbers_list)

Numbers smaller than 10 : [8, 3, 7]

## 3. Largest Element in a List

Naive Soln.:

In [61]:
# Function to find the maximum value in a list
def get_max_value(lst):
    for current_element in lst:        # Iterate through each element in the list
        for comparison_element in lst:  # Compare with each element in the list
            if comparison_element > current_element:  # Check if any element is greater
                break
        else:                           # If loop completes without break, no greater element found
            return current_element

    return None  # Return None if no maximum value is found

# Given list of integers
input_list = [10, 5, 20, 8, 15, 2, 30]

# Find and print the maximum value using the function
max_value = get_max_value(input_list)
print("Maximum value:", max_value)

Maximum value: 30

Efficient Approach:

In [62]:
# Function to find the maximum value in a list
def get_max_value(lst):
    if not lst:                # Check if the list is empty
        return None            # Return None if the list is empty
    else:
        result = lst[0]        # Assume the first element is the maximum

        # Iterate through the list from index 1 to the last element
        for i in range(1, len(lst)):
            if lst[i] > result:  # Compare current element with the assumed maximum
                result = lst[i]  # Update result if the current element is greater

        return result           # Return the maximum value

# Given list of integers
input_list = [10, 5, 20, 8, 15, 2, 30]

# Find and print the maximum value using the function
max_value = get_max_value(input_list)
print("Maximum value:", max_value)

Maximum value: 30

Using Built-in Function:

In [63]:
# Given list of integers
input_list = [10, 5, 20, 8, 15, 2, 30]

# Find and print the maximum value using the function
max_value = max(input_list)
print("Maximum value:", max_value)

Maximum value: 30

## 4. Get Second Largest Element in List

Solution with Two Traversal

In [64]:
def get_max(l):
    """
    Find the maximum element in the list.

    Args:
        l (list): The input list of integers.

    Returns:
        int or None: The maximum element in the list, or None if the list is empty.
    """
    if not l:
        return None
    else:
        res = l[0]                  # Assume l[0] is the maximum

        # Iterate through the list from index 1 to the last
        for i in range(1, len(l)):
            if l[i] > res:           # Check whether the current element is greater than res
                res = l[i]          # If the current element is greater, update res to current

        return res

def get_second_max(l):
    """
    Find the second maximum element in the list.

    Args:
        l (list): The input list of integers.

    Returns:
        int or None: The second maximum element in the list, or None if there are fewer than two elements.
    """
    if len(l) <= 1:
        return None

    largest = get_max(l)  # Get the largest element using the get_max function
    second_largest = None

    for x in l:
        if x != largest:
            if second_largest is None:
                second_largest = x
            else:
                second_largest = max(x, second_largest)

    return second_largest

# Given list of integers
input_list = [10, 5, 20, 8, 15, 2, 30]

# Find and print the second maximum value using the function
second_max_value = get_second_max(input_list)
print("Second maximum value:", second_max_value)

Second maximum value: 20

Solution with One Traversal

In [65]:
def get_second_max(lst):
    """
    Find the second maximum element in the given list.

    Args:
        lst (list): The input list of integers.

    Returns:
        int or None: The second maximum element in the list, or None if there are fewer than two elements.
    """
    if len(lst) <= 1:
        return None

    largest = lst[0]  # Assume the first element is the largest
    second_largest = None

    # Iterate through the list starting from the second element
    for x in lst[1:]:
        if x > largest:          # Check if the current element is greater than the largest
            second_largest = largest  # Update the second largest with the previous largest
            largest = x         # Update the largest with the current element

        elif x != largest:      # If x is not the largest element
            if second_largest is None or second_largest < x:  # Check if x is greater than the current second largest
                second_largest = x  # Update the second largest with the current element

    return second_largest

# Given list of integers
input_list = [10, 5, 20, 8, 15, 2, 30]

# Find and print the second maximum value using the function
second_max_value = get_second_max(input_list)
print("Second maximum value:", second_max_value)

Second maximum value: 20

## 5. Check if List is Sorted (aesc)

In [66]:
def is_sorted(lst):
    """
    Check if the given list is sorted in ascending order.

    Args:
        lst (list): The input list of elements.

    Returns:
        bool: True if the list is sorted, False otherwise.
    """
    sorted_lst = sorted(lst)  # Create a sorted version of the list

    if lst == sorted_lst:     # Compare the original list with the sorted list
        return True           # If they are the same, the list is sorted
    else:
        return False          # Otherwise, the list is not sorted

# Given list of elements
input_list = [10, 20, 30, 15, 40]

if is_sorted(input_list):
    print("Yes, the list is sorted.")
else:
    print("No, the list is not sorted.")

No, the list is not sorted.

## 6. Reversing List in Python

In [67]:
# Original list
l = [10, 20, 30]

# Method 1: Using the reverse() method in-place
l.reverse()     # Reverse the given list in-place
print("Method 1 - Reversed list (in-place):", l)

# Method 2: Using the reversed() function to create a new reversed list
l = [10, 20, 30]   # Restore the original list
new_l = list(reversed(l))   # Create a new reversed list using the reversed() function
print("Method 2 - New reversed list (reversed()):", new_l)

# Method 3: Using slicing to create a new reversed list
l = [10, 20, 30]   # Restore the original list
new_l = l[::-1]             # Create a new reversed list using slicing
print("Method 3 - New reversed list (slicing):", new_l)

# Method 4: Custom Function
def reverse_array(arr, n):
    """
    Reverse the given array in-place.

    Args:
        arr (list): The input list of elements to be reversed.
        n (int): The size of the array.

    Returns:
        list: The reversed array.
    """
    start = 0      # Initialize the starting index
    end = n - 1    # Initialize the ending index

    while start < end:
        # Swap the elements at the start and end indices
        arr[start], arr[end] = arr[end], arr[start]
        start += 1   # Move the start index towards the end
        end -= 1     # Move the end index towards the start

    return arr      # Return the reversed array

# Given array
arr = [1, 2, 3, 4, 5]
n = len(arr)   # Calculate the size of the array

# Reverse the array using the function
reversed_arr = reverse_array(arr, n)
print("Method 4: Reversed array:", reversed_arr)

Method 1 - Reversed list (in-place): [30, 20, 10]
Method 2 - New reversed list (reversed()): [30, 20, 10]
Method 3 - New reversed list (slicing): [30, 20, 10]
Method 4: Reversed array: [5, 4, 3, 2, 1]

## 7. Removing Duplicates

Naive Approach

In [68]:
def remove_duplicates(arr, n):
    """
    Remove duplicates from the given array and return the new length after removing duplicates.

    Args:
        arr (list): The input array containing duplicate elements.
        n (int): The original length of the array.

    Returns:
        int: The new length of the array after removing duplicates.
    """
    temp = [0] * n      # Create a temporary array to store non-duplicate elements
    temp[0] = arr[0]    # The first element is always non-duplicate
    res = 1             # Initialize the result (new length) as 1

    # Iterate through the array starting from the second element
    for i in range(1, n):
        if temp[res - 1] != arr[i]:  # Check if the current element is different from the last element in temp
            temp[res] = arr[i]       # Store the current element in temp
            res += 1                  # Increment the result (new length)

    # Copy the non-duplicate elements from temp back to arr
    for i in range(0, res):
        arr[i] = temp[i]

    return res  # Return the new length after removing duplicates

# Example usage
n = 7
arr = [10, 20, 20, 30, 30, 30, 30]
new_length = remove_duplicates(arr, n)
print("New length after removing duplicates:", new_length)

New length after removing duplicates: 3

Efficient Approach

In [69]:
def remove_duplicates(arr, n):
    """
    Remove duplicates from the given array and return the new length after removing duplicates.

    Args:
        arr (list): The input array containing duplicate elements.
        n (int): The original length of the array.

    Returns:
        int: The new length of the array after removing duplicates.
    """
    temp = [0] * n      # Create a temporary array to store non-duplicate elements
    temp[0] = arr[0]    # The first element is always non-duplicate
    res = 1             # Initialize the result (new length) as 1

    # Iterate through the array starting from the second element
    for i in range(1, n):
        if temp[res - 1] != arr[i]:  # Check if the current element is different from the last element in temp
            temp[res] = arr[i]       # Store the current element in temp
            res += 1                  # Increment the result (new length)

    # Copy the non-duplicate elements from temp back to arr
    for i in range(0, res):
        arr[i] = temp[i]

    return res  # Return the new length after removing duplicates

# Example usage
n = 7
arr = [10, 20, 20, 30, 30, 30, 30]
new_length = remove_duplicates(arr, n)
print("Original array:", arr)
print("New length after removing duplicates:", new_length)

Original array: [10, 20, 30, 30, 30, 30, 30]
New length after removing duplicates: 3

## 8. Left Rotate a List by One

In [70]:
# Original list
l = [10, 20, 30, 40]

# Method 1: Using list slicing to left rotate by one position
l = l[1:] + l[0:1]  # Move all elements except the first one to the end and append the first element
print("Method 1 - Left rotated list:", l)

# Method 2: Using append() and pop() to left rotate by one position
l = [10, 20, 30, 40]  # Restore the original list
first_element = l.pop(0)  # Remove the first element and store it
l.append(first_element)   # Append the first element to the end
print("Method 2 - Left rotated list:", l)

Method 1 - Left rotated list: [20, 30, 40, 10]
Method 2 - Left rotated list: [20, 30, 40, 10]

## 9. Get Element At Index

In [71]:
def get_element_at_index(arr, i):
    """
    Get the element at a specific index in the array.

    Args:
        arr (list): The input array.
        i (int): The index to retrieve the element from.

    Returns:
        int: The element at the specified index, or -1 if the index is out of range.
    """
    n = len(arr)  # Get the size of the array
    if 0 <= i < n:  # Check if the index is within the valid range [0, n-1]
        return arr[i]  # Return the element at the specified index
    else:
        return -1  # Return -1 if the index is out of range

# Example usage
arr = [10, 20, 30, 40, 50]
index = 2
result = get_element_at_index(arr, index)
print("Element at index", index, ":", result)

Element at index 2 : 30

## 10. Update Element At Index

In [72]:
def updateArray(arr, n, idx, element):
    """
    Update the element at the given index in the array with the specified element.

    Args:
        arr (list): The input array to be updated.
        n (int): The size of the array.
        idx (int): The index at which the element needs to be updated.
        element: The new element to be placed at the specified index.

    Returns:
        list: The updated array after modifying the element at the specified index.
    """
    arr[idx] = element  # Update the element at the specified index
    return arr  # Return the updated array

# Example usage
n = 5
array = [1, 2, 3, 4, 5]
index = 2
new_element = 10
updated_array = updateArray(array, n, index, new_element)
print("Updated array:", updated_array)

Updated array: [1, 2, 10, 4, 5]

## 11. Array Delete And Shift

In [73]:
def deleteFromArray(arr, n, idx):
    """
    Delete the element at the specified index from the array and print the modified array.

    Args:
        arr (list): The input array from which the element needs to be deleted.
        n (int): The size of the array.
        idx (int): The index of the element to be deleted.

    Returns:
        None
    """
    if idx < 0 or idx >= n:
        print("Invalid index")  # Print an error message for invalid index
        return

    del arr[idx]  # Delete the element at the specified index

    print("Modified array:", arr)  # Print the modified array

# Example usage
n = 5
array = [1, 2, 3, 4, 5]
index = 2
deleteFromArray(array, n, index)

Modified array: [1, 2, 4, 5]

## 12. Mean And Median of Array

In [74]:
def find_median(arr):
    """
    Calculate and return the median of the given array.

    Args:
        arr (list): The input list of numbers.

    Returns:
        int: The calculated median.
    """
    arr.sort()  # Sort the array
    length = len(arr)
    if length % 2 == 0:
        median = int((arr[length//2] + arr[(length//2)-1]) // 2)
    else:
        median = int(arr[length//2])
    return median

def find_mean(arr):
    """
    Calculate and return the mean of the given array.

    Args:
        arr (list): The input list of numbers.

    Returns:
        int: The calculated mean.
    """
    mean = int(sum(arr) / len(arr))
    return mean

# Given array
arr = [10, 5, 20, 8, 15, 2, 30]

# Calculate and print the median
median_value = find_median(arr)
print("Median:", median_value)

# Calculate and print the mean
mean_value = find_mean(arr)
print("Mean:", mean_value)

Median: 10
Mean: 12

## 13. Count Smaller Than X

In [75]:
def smaller_than_x(arr, n, x):
    """
    Count the number of elements in the array that are strictly smaller than x.

    Args:
        arr (list): The input list of non-negative integers.
        n (int): The size of the array.
        x (int): The threshold integer to compare with.

    Returns:
        int: The count of elements smaller than x.
    """
    # Create a list of elements that are smaller than x
    listed = [i for i in arr if i < x]

    # Return the count of elements in the list
    return len(listed)

# Given array and threshold integer
arr = [10, 5, 20, 8, 15, 2, 30]
x = 15

# Calculate and print the count of elements smaller than x
count = smaller_than_x(arr, len(arr), x)
print("Count of elements smaller than", x, ":", count)

Count of elements smaller than 15 : 4

## 14. Find Immediate Smaller Than X

In [76]:
def immediate_smaller_than_x(arr, n, x):
    """
    Find the element in the array which is smaller than x and closest to it.

    Args:
        arr (list): The input list of positive integers.
        n (int): The size of the array.
        x (int): The threshold integer to compare with.

    Returns:
        int: The element in the array smaller than x and closest to it.
    """
    immediate_smaller = None

    # Iterate through the array to find the immediate smaller element
    for num in arr:
        if num < x:
            if immediate_smaller is None or (x - num) < (x - immediate_smaller):
                immediate_smaller = num

    return immediate_smaller

# Given array and threshold integer
arr = [10, 5, 20, 8, 15, 2, 30]
x = 16

# Find and print the element smaller than x and closest to it
result = immediate_smaller_than_x(arr, len(arr), x)
print("Immediate smaller element than", x, ":", result)

Immediate smaller element than 16 : 15

## 15. Count Elements Greater Than X

In [77]:
def greater_than_x(arr, n, x):
    """
    Count the number of elements in the array that are strictly greater than x.

    Args:
        arr (list): The input list of non-negative integers.
        n (int): The size of the array.
        x (int): The threshold integer to compare with.

    Returns:
        int: The count of elements in the array that are strictly greater than x.
    """
    # Create a new list containing elements greater than x
    new_list = [i for i in arr if i > x]

    # Return the count of elements in the new list
    return len(new_list)

# Given array and threshold integer
arr = [10, 5, 20, 8, 15, 2, 30]
x = 12

# Count and print the number of elements greater than x
result = greater_than_x(arr, len(arr), x)
print("Number of elements greater than", x, ":", result)

Number of elements greater than 12 : 3

## 16. Find Immediate Greater Than X

In [78]:
def immediate_greater(arr, n, x):
    """
    Find the value in the array that is greater than x and closest to it.

    Args:
        arr (list): The input list of positive integers.
        n (int): The size of the array.
        x (int): The threshold integer to compare with.

    Returns:
        int: The value in the array that is greater than x and closest to it, or -1 if no such value exists.
    """
    arr = sorted(arr)  # Sort the array in ascending order

    for i in arr:
        if i > x:
            return i  # Return the first value greater than x
            break
        else:
            continue

    # If no value greater than x is found, return -1
    if x > max(arr):
        return -1

# Given array and threshold integer
arr = [10, 5, 20, 8, 15, 2, 30]
x = 12

# Find and print the value greater than x and closest to it
result = immediate_greater(arr, len(arr), x)
print("Value greater than", x, "and closest to it:", result)

Value greater than 12 and closest to it: 15

## 17. Find the Majority

In [79]:
def find_most_frequent(arr, x, y):
    """
    Find the element that appears most frequently in the array. If both elements have the same frequency, return the smaller element.

    Args:
        arr (list): The input list of integers.
        x (int): The first element.
        y (int): The second element.

    Returns:
        int: The element that appears most frequently in the array. If both elements have the same frequency, return the smaller element.
    """
    freq_x = arr.count(x)  # Count the frequency of element x
    freq_y = arr.count(y)  # Count the frequency of element y

    if freq_x > freq_y:
        return x
    elif freq_y > freq_x:
        return y
    else:
        return min(x, y)

# Given array and elements x and y
arr = [1, 1, 2, 2, 3, 3, 4, 4, 4, 4, 5]
x = 4
y = 5

# Find and print the element that appears most frequently
result = find_most_frequent(arr, x, y)
print("Element that appears most frequently:", result)

Element that appears most frequently: 4

## 18. Rotate Array

In [80]:
def rotate_left(arr, n, d):
    """
    Rotate the given array to the left by D steps.

    Args:
        arr (list): The input list of elements to be rotated.
        n (int): The size of the array.
        d (int): The number of steps to rotate the array.

    Returns:
        list: The rotated array.
    """
    d = d % n  # Calculate the effective rotation steps within the array size

    # Slice the array into two parts and swap them
    rotated_arr = arr[d:] + arr[:d]

    return rotated_arr  # Return the rotated array

# Given array and rotation steps
arr = [1, 2, 3, 4, 5]
n = len(arr)  # Calculate the size of the array
d = 2        # Number of steps to rotate the array

# Rotate the array using the function
rotated_array = rotate_left(arr, n, d)
print("Rotated array:", rotated_array)

Rotated array: [3, 4, 5, 1, 2]

![360_F_291522205_XkrmS421FjSGTMRdTrqFZPxDY19VxpmL.jpg]()