![download (4).png]()

<div align="center">
  <font color="blue"><h1>Mathematical Approach Based Questions</h1></font>
</div>

# 1. Sum of Natural numbers

In [1]:
# Function to calculate the sum of the first 'n' natural numbers
def sum_natural(n):
    return (n * (n + 1) / 2)  # Use the formula for the sum of an arithmetic series

In [2]:
Test_case = [5, 7, 898]
for i in Test_case:
  print(sum_natural(i))

15.0
28.0
403651.0

### ========================================================================================

# 2. Count Digits

In [3]:
# Function to count the number of digits in a given number 'n'
def count_digit(n):
    num = 0  # Initialize the digit count to 0

    while n > 0:
        num += 1  # Increment the digit count for each digit encountered
        n = n // 10  # Remove the last digit from 'n'

    return num  # Return the total number of digits

# Example usage
number = 12345
digit_count = count_digit(number)
print(f"Number of digits in {number}: {digit_count}")

Number of digits in 12345: 5

In [4]:
Test_case = [5, 1234567897, 898]
for i in Test_case:
  print(count_digit(i))

1
10
3

### ========================================================================================

# 3. Palindrome Number [[Leetcode]](https://leetcode.com/problems/palindrome-number/)

In [5]:
# Function to check if a number is a palindrome
def ispalindrome(number):
    temp = number  # Placeholder to store the original number
    rev = 0  # Variable to store the reverse of the number

    while temp > 0:
        ld = temp % 10  # Extract the last digit
        rev = 10 * rev + ld  # Build the reverse number by adding the last digit
        temp = temp // 10  # Remove the last digit from the original number

    return rev == number  # Return whether the reversed number is equal to the original number

In [6]:
Test_case = [7887, 12, 7, 121]
for i in Test_case:
  print(ispalindrome(i))

True
False
True
True

### ========================================================================================

# 4. Factorial of a number

In [7]:
def factorial_normal(number): #Naive Approach
  fact = 1
  for i in range(2,number+1):
    fact *=i
  return fact

def recursive_fact(i):
  if i==0:
    return 1
  elif i == 1:
    return 1
  else:
    return i*recursive_fact(i-1)

In [8]:
Test_case = [5, 12, 1]
for i in Test_case:
  print(factorial_normal(i))

120
479001600
1

In [9]:
Test_case = [5, 12, 1]
for i in Test_case:
  print(recursive_fact(i))

120
479001600
1

### ========================================================================================

# 5. Factorial Trailing Zeroes
[[Leetcode]](https://leetcode.com/problems/factorial-trailing-zeroes/description/)

Naive Approach

In [10]:
def trailingZeroes(n):
  #Naive Approach
  fact=1
  for i in range(2,n+1):
    fact*=i
  res=0
  while fact%10 == 0:
    res+=1
    fact = fact // 10
  return res

In [11]:
Test_case = [5, 12, 189]
for i in Test_case:
  print(trailingZeroes(i))

1
2
45

Optimized Approach

In [12]:

# Function to count the number of trailing zeroes in n!
def trailingZeroes(n):
    count = 0  # Initialize the count of trailing zeroes
    divby = 5  # Initialize the divisor (powers of 5)

    while (int(n / divby) > 0):
        # Add the number of multiples of divby in n to the count
        count += int(n / divby)  # [n/5] + [n/25] + [n/125] + ...
        divby *= 5  # Increase the divisor to its next power of 5

    return count  # Return the total count of trailing zeroes

# Example usage
n = 25
zeroes_count = trailingZeroes(n)
print(f"Number of trailing zeroes in {n}! is {zeroes_count}")

Number of trailing zeroes in 25! is 6

In [13]:
Test_case = [5, 12, 189]
for i in Test_case:
  print(trailingZeroes(i))

1
2
45

### ========================================================================================

# 6. GCD or HCF of two numbers

**Naive Approach**

In [14]:
def gcd(a,b):

  while a!=b:
    if a>b:
      a=a-b
    else:
      b=b-a
  return a

In [15]:
gcd(7,14)

7

Recursive Approach

In [16]:
# Function to find the Greatest Common Divisor (GCD) using Euclidean algorithm
def gcd(a, b):
    if b == 0:
        return a  # If b is 0, the GCD is a
    return gcd(b, a % b)  # Recursively find the GCD by swapping a and b

In [17]:
gcd(7,13)

1

### ========================================================================================

# 7. LCM

Naive Approach

In [18]:
#Naive
def lcm(a,b):
  res=max(a,b)
  while True:
    if res%a==0 and res%b==0:
      return res

    res+=1
  return res

In [19]:
lcm(4,12)

12

Optimized Approach

In [20]:
# Function to find the Greatest Common Divisor (GCD) using Euclidean algorithm
def gcd(a, b):
    if b == 0:
        return a  # GCD of a and 0 is a
    return gcd(b, a % b)  # Recursively find GCD

# Function to find the Least Common Multiple (LCM) using optimized formula
def lcm_optimized(a, b):
    return a * b / gcd(a, b)  # LCM = (a * b) / GCD(a, b)

# Example usage
num1 = 12
num2 = 18

# Calculate and print the LCM of num1 and num2
lcm_result = lcm_optimized(num1, num2)
print(f"LCM of {num1} and {num2} is {lcm_result}")

LCM of 12 and 18 is 36.0

### ========================================================================================

# 8. Check Prime

Naive Approach

In [21]:
def prime_check(n):
  if n==1:
    return False
  for i in range(2,n):
    if n%i==0:
      return False

  return True

In [22]:
Test_case = [5, 12, 29]
for i in Test_case:
  print(prime_check(i))

True
False
True

Optimized Approach

In [23]:
def isprime(n):
  if n==1:
    return False
  i=2
  while (i*i <= n):
    if n%i == 0:
      return False
    i+=1
  return True

In [24]:
Test_case = [5, 12, 29]
for i in Test_case:
  print(isprime(i))

True
False
True

Super Efficient Approach

In [25]:
def isPrime(n):
    """
    Check if a given number 'n' is a prime number using an optimized approach.

    Args:
        n (int): The number to be checked for primality.

    Returns:
        bool: True if 'n' is prime, False otherwise.

    Algorithm and Approach:
        1. If 'n' is 1, return False (1 is not a prime number).
        2. If 'n' is 2 or 3, return True (2 and 3 are prime numbers).
        3. If 'n' is divisible by 2 or 3, return False (optimized prime check).
        4. Initialize 'i' to 5 for prime checking starting from 5:
            a. Loop while 'i * i' is less than or equal to 'n':
                - If 'n' is divisible by 'i' or 'i + 2', return False (optimized prime check).
            b. Increment 'i' by 6 (5, 11, 17, 23, ...).
                - This step optimizes the loop by skipping numbers divisible by 2 and 3,
                  and by handling 'i + 2' divisors in the next iteration.
        5. If 'n' is not divisible by any factors, return True (it's prime).

    Example:
        >>> test_numbers = [1, 2, 7, 15, 29, 49, 97]
        >>> for num in test_numbers:
        >>>     if isPrime(num):
        >>>         print(num, "is a prime number.")
        2 is a prime number.
        7 is a prime number.
        29 is a prime number.
        97 is a prime number.
    """
    if n == 1:
        return False  # 1 is not a prime number
    if n == 2 or n == 3:
        return True  # 2 and 3 are prime numbers
    if n % 2 == 0 or n % 3 == 0:
        return False  # If divisible by 2 or 3, it's not prime

    i = 5
    while (i * i <= n):
        if n % i == 0 or n % (i + 2) == 0:
            return False  # If divisible by current i or i+2, not prime
        i += 6  # Incremented by 6 to optimize prime checking
                # Since i+2 is covered in the next step and we skip divisors divisible by 2 and 3
                # This pattern handles 5, 11, 17, 23, 29, ...
    return True  # If not divisible by any factors, it's prime

# Example usage
test_numbers = [1, 2, 7, 15, 29, 49, 97]

for num in test_numbers:
    if isPrime(num):
        print(num, "is a prime number.")

    else:
        print(num, "is not a prime number.")

1 is not a prime number.
2 is a prime number.
7 is a prime number.
15 is not a prime number.
29 is a prime number.
49 is not a prime number.
97 is a prime number.

### ========================================================================================

# 9. Prime Factorization

In [26]:
def isPrime(n):
    """
    Check if a given number 'n' is a prime number using a basic approach.

    Args:
        n (int): The number to be checked for primality.

    Returns:
        bool: True if 'n' is prime, False otherwise.

    Algorithm and Approach:
        1. Loop through numbers from 2 to 'n - 1':
            a. If 'n' is divisible by 'i', return False (not prime).
        2. If 'n' is not divisible by any numbers in the loop, return True (prime).

    Example:
        >>> isPrime(17)
        True
    """
    for i in range(2, n):
        if n % i == 0:
            return False  # If n is divisible by any number other than 1 and itself, it's not prime
    return True

def printFactors(n):
    """
    Print the prime factors of a given number 'n'.

    Args:
        n (int): The number for which prime factors are to be printed.

    Returns:
        None: Prints the prime factors of 'n'.

    Algorithm and Approach:
        1. Loop through numbers from 2 to 'n':
            a. If 'i' is prime, start a loop while 'n' is divisible by 'i':
                - Print 'i' as a prime factor.
                - Multiply 'x' by 'i' to find the next occurrence.
        2. The prime factors of 'n' are printed.

    Example:
        >>> n = 72
        >>> print("Prime factors of", n, ":")
        >>> printFactors(n)
        Prime factors of 72 :
        2
        3
    """
    for i in range(2, n + 1):
        if isPrime(i):
            x = i
            while n % x == 0:
                print(i)  # Print the prime factor
                x *= i  # Multiply x by i to find the next occurrence

# Example usage
n = 72
print("Prime factors of", n, ":")
printFactors(n)

Prime factors of 72 :
2
2
2
3
3

### ========================================================================================

# 10. Print all Divisors

Naive Approach

In [27]:
def print_divisors(n):
  for i in range(1,n+1):
    if n%i==0:
      print(i)

In [28]:
Test_case = [5,67, 81, 92, 125,149]
for i in Test_case:
  print(print_divisors(i))

1
5
None
1
67
None
1
3
9
27
81
None
1
2
4
23
46
92
None
1
5
25
125
None
1
149
None

Efficient Solution

In [29]:
def printDivisors(n):
  i=1
  while (i*i<=n):
    if n%i == 0:
      print(i)
      if (i!=n/i):
        print(int(n/i)) #remember divisors always occur in pairs
    i+=1

In [30]:
Test_case = [5,67, 81, 92, 125,149]
for i in Test_case:
  print(printDivisors(i))

1
5
None
1
67
None
1
81
3
27
9
None
1
92
2
46
4
23
None
1
125
5
25
None
1
149
None

Super Efficient Approach:

In [31]:
def printdivisors(n):
    """
    Print all the divisors of a given number 'n' in ascending order.

    Args:
        n (int): The number for which divisors are to be printed.

    Returns:
        None: Prints the divisors of 'n'.

    Algorithm and Approach:
        1. Initialize 'i' to 1 for iteration.
        2. Loop through potential divisors from 1 to the square root of 'n':
            a. If 'n' is divisible by 'i', print 'i' as a divisor.
            b. Increment 'i' for the next iteration.
        3. Decrement 'i' to the last value used in the previous loop.
        4. Loop through potential divisors from the square root of 'n' down to 1:
            a. Check if 'n' is divisible by 'i' and 'i' is not equal to 'n' divided by 'i' (to avoid duplicates).
            b. Print the divisor 'n / i'.
            c. Decrement 'i' to move to the next divisor in reverse order.

    Example:
        >>> print("Divisors of 36:")
        >>> printdivisors(36)
        1
        2
        3
        4
        6
        9
        12
        18
        36
    """
    i = 1  # Initialize 'i' for iteration

    # Loop through divisors from 1 to sqrt(n)
    while (i * i <= n):
        if n % i == 0:
            print(i)  # Print divisor
        i += 1

    i -= 1  # Decrement 'i' to the last value used in the previous loop

    # Loop through divisors from sqrt(n) down to 1
    while (i >= 1):
        # Check if n is divisible by i and i is not n/i (to avoid duplicates)
        if (n % i == 0 and i != n / i):
            print(int(n / i))  # Print the other divisor
        i -= 1  # Move to the next divisor in reverse order

# Example usage
print("Divisors of 36:")
printdivisors(49)

Divisors of 36:
1
7
49

### ========================================================================================

# 11. Sieve of Eratosthens (Find all prime numbers upto n)

Naive Approach

In [32]:
# Function to check if a number is prime
def isPrime(n):
    if n == 1:
        return False  # 1 is not a prime number
    if n == 2 or n == 3:
        return True  # 2 and 3 are prime numbers
    if n % 2 == 0 or n % 3 == 0:
        return False  # If divisible by 2 or 3, it's not prime

    # Using 6k +/- 1 optimization for primality testing
    i = 5
    while (i * i <= n):
        if n % i == 0 or n % (i + 2) == 0:
            return False  # If divisible by current i or i+2, not prime
        i += 6
    return True  # If not divisible by any factors, it's prime

# Function to print prime numbers up to n
def printPrime(n):
    found_prime = False  # Variable to track if any prime is found
    for i in range(2, n + 1):
        if isPrime(i):
            found_prime = True
            print(i, end=" ")  # Print the prime number
    return found_prime  # Return whether any prime was found

# List of test cases
Test_case = [21, 28, 19]

# Loop through each test case
for i in Test_case:
    print("Prime numbers for", i, ":", end=" ")  # Print the test case label
    found = printPrime(i)  # Call the function to print prime numbers up to i
    if not found:
        print("No prime numbers found.")
    print()  # Print a new line after each test case

Prime numbers for 21 : 2 3 5 7 11 13 17 19
Prime numbers for 28 : 2 3 5 7 11 13 17 19 23
Prime numbers for 19 : 2 3 5 7 11 13 17 19

Efficient Approach

In [33]:
# Function to find prime numbers using the Sieve of Eratosthenes algorithm
def seive(n):
    isPrime = [True] * (n + 1)  # Initialize a list to mark numbers as prime or not

    i = 2  # Start with the smallest prime number
    while i * i <= n:  # Iterate until the square of i is within the range
        if isPrime[i]:  # If i is marked as prime
            # Mark all multiples of i as not prime
            for j in range(2 * i, n + 1, i):
                isPrime[j] = False  # Mark j (multiple of i) as not prime

        i += 1  # Move to the next number

    # Print the prime numbers
    for i in range(2, n + 1):
        if isPrime[i]:  # If i is marked as prime
            print(i, end=" ")  # Print the prime number

# Example usage
limit = 50
print(f"Prime numbers up to {limit}:")
seive(limit)

Prime numbers up to 50:
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47

Super Efficient Approach

In [34]:
def seive(n):
    """
    Find and print prime numbers up to 'n' using the Sieve of Eratosthenes algorithm.

    Args:
        n (int): The upper limit up to which prime numbers are to be found.

    Returns:
        None: Prints the prime numbers up to 'n'.

    Algorithm Steps:
        1. Check if 'n' is less than or equal to 1. If true, return early as there are no prime numbers in this range.
        2. Initialize a boolean list 'isPrime' of size (n + 1) with all elements marked as True, indicating they are potentially prime.
        3. Start with the smallest prime number 'i = 2' and iterate through numbers up to 'n':
            a. If 'i' is marked as prime ('isPrime[i]' is True), print 'i' as a prime number.
            b. For each prime number 'i', mark all multiples of 'i' as not prime by setting 'isPrime[j]' to False.
               The loop runs from 'i * i' up to 'n' in increments of 'i'.
            c. Move to the next number by incrementing 'i'.
        4. This process prints all prime numbers up to 'n'.

    Example:
        >>> seive(50)
        Prime numbers up to 50:
        2 3 5 7 11 13 17 19 23 29 31 37 41 43 47
    """
    if n <= 1:
        return  # No prime numbers if 'n' is less than or equal to 1

    isPrime = [True] * (n + 1)  # Create a boolean list to mark numbers as prime or not

    i = 2  # Start with the smallest prime number
    while i <= n:  # Iterate through numbers up to 'n'
        if isPrime[i]:  # If 'i' is marked as prime
            print(i, end=" ")  # Print the prime number 'i'

            # Mark all multiples of 'i' as not prime
            for j in range(i * i, n + 1, i):
                isPrime[j] = False

        i += 1  # Move to the next number

# Example usage
limit = 50
print(f"Prime numbers up to {limit}:")
seive(limit)

Prime numbers up to 50:
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47

### ========================================================================================

# 12. Computation of Power

**Naive Approach**

In [35]:
def power(x, n):
    # Calculate the value of 'x' raised to the power of 'n'

    result = 1  # Initialize result to store the calculated power

    if n == 0:
        result = 0  # If n is 0, the result is 0 (x^0 = 1)
    else:
        for i in range(1, n + 1):
            result *= x  # Multiply 'result' by 'x' 'n' times to calculate power

    return result  # Return the calculated result

# Example usage
base = 2
exponent = 3
result = power(base, exponent)
print(f"{base} raised to the power of {exponent} is {result}")

2 raised to the power of 3 is 8

Efficient Approach

In [36]:
def power(x, n):
    """
    Calculate the value of 'x' raised to the power of 'n' using a recursive approach.

    Args:
        x (int): The base number.
        n (int): The exponent.

    Returns:
        int: The result of 'x' raised to the power of 'n'.

    Algorithm and Approach:
        1. If 'n' is 0, return 1 (x^0 = 1).
        2. Calculate 'temp' by recursively calling 'power' function with 'x' and 'n // 2'.
        3. Update 'temp' by squaring it: 'temp' = 'temp' * 'temp'.
        4. If 'n' is even (n % 2 == 0), return 'temp'.
        5. If 'n' is odd, multiply 'temp' by 'x' and return the result.
        6. The algorithm uses recursion and the property (x^n) * (x^n) = x^(2n) to optimize calculations.

    Example:
        >>> power(2, 3)
        8
    """
    if n == 0:
        return 1  # Base case: x^0 = 1

    temp = power(x, n // 2)  # Recursive call with halved exponent

    temp = temp * temp  # Square 'temp' to utilize the property (x^n) * (x^n) = x^(2n)

    if n % 2 == 0:  # If 'n' is even
        return temp

    # If 'n' is odd, multiply 'temp' by 'x'
    return temp * x

# Example usage
base = 2
exponent = 3
result = power(base, exponent)
print(f"{base} raised to the power of {exponent} is {result}")

2 raised to the power of 3 is 8

### Iterative Approach

In [37]:
def power(x, n):
    """
    Calculate the value of 'x' raised to the power of 'n' using an efficient iterative approach.

    Args:
        x (int): The base number.
        n (int): The exponent.

    Returns:
        int: The result of 'x' raised to the power of 'n'.

    Algorithm and Approach:
        1. Initialize 'res' to 1 to store the calculated power.
        2. Loop while 'n' is greater than 0:
            a. If 'n' is odd (n % 2 != 0), multiply 'res' by 'x'.
            b. Square 'x' to calculate 'x' raised to the power of 2.
            c. Halve 'n' by integer division (n // 2).
        3. The final value of 'res' is the result of 'x' raised to the power of 'n'.

    Example:
        To calculate 2^5:
        - Initialize res = 1
        - Loop 1: n = 5 is odd, so res = res * x = 1 * 2 = 2, x = x * x = 2 * 2 = 4, n = n // 2 = 2
        - Loop 2: n = 2 is even, so x = x * x = 4 * 4 = 16, n = n // 2 = 1
        - Loop 3: n = 1 is odd, so res = res * x = 2 * 16 = 32, x = x * x = 16 * 16 = 256, n = n // 2 = 0 (exit loop)
        - Final res = 32, which is 2^5

    Example usage:
    >>> base = 2
    >>> exponent = 5
    >>> result = power(base, exponent)
    >>> print(f"{base} raised to the power of {exponent} is {result}")  # Output: 2 raised to the power of 5 is 32
    """
    res = 1  # Initialize 'res' to store the calculated power

    while n > 0:
        if n % 2 != 0:  # If 'n' is odd
            res = res * x  # Multiply 'res' by 'x'

        x = x * x  # Square 'x' to calculate 'x' raised to the power of 2
        n = n // 2  # Halve 'n' by integer division

    return res  # Return the calculated result

# Example usage
base = 2
exponent = 5
result = power(base, exponent)
print(f"{base} raised to the power of {exponent} is {result}")

2 raised to the power of 5 is 32

# Thank You